### ISSUE TITLE
Dockerfile with Healthcheck

### ISSUE THREAD

**Issue by trickert76** [amm0nite/mqtt2http#9]
I'm not sure, if you want, but I'm using the health state of running docker images to monitor them via simple Docker API checks. I see, you've exposed a Prometheus check, but I don't use it.

If you want, you could update your Dockerfile a bit. Mine is now:

```
# Build stage
FROM golang:1.24.3-alpine AS build
RUN apk add --no-cache ca-certificates

ENV CGO_ENABLED=0 \
    GOOS=linux

WORKDIR /workspace

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
RUN go build -v -o app ./cmd/mqtt2http.go

# Run stage
FROM alpine

ENV MQTT2HTTP_MQTT_LISTEN_ADDRESS=:1883 \
    MQTT2HTTP_HTTP_LISTEN_ADDRESS=:8080 \
    MQTT2HTTP_METRICS_HTTP_LISTEN_ADDRESS=:9090 \
    MQTT2HTTP_AUTHORIZE_URL=http://example.com \
    MQTT2HTTP_PUBLISH_URL=http://example.com/{topic} \
    MQTT2HTTP_CONTENT_TYPE=application/octet-stream \
    MQTT2HTTP_TOPIC_HEADER=X-Topic

RUN apk add --no-cache ca-certificates curl && \
    adduser -D mqtt2http

USER mqtt2http
WORKDIR /home/mqtt2http

COPY --from=build /workspace/app ./

CMD ["./app"]

HEALTHCHECK --interval=3600s --timeout=5s --start-period=10s CMD \
  curl --fail http://localhost${MQTT2HTTP_HTTP_LISTEN_ADDRESS}/ || exit 1  
```

So, it reduces one layer (only one RUN command), changed the user from app to mqtt2http, added the ENV vars as default and added the healthcheck. Of course last one only works, when there is really a env var and not a env-file. I didn't yet removed that check.

I'll not make a PR here. Everyone has different tastes and it's very optional and could also be solved outside the image, like I did with homebridge

```
  homebridge:
    image: "docker.io/homebridge/homebridge:latest"
    restart: "unless-stopped"
    network_mode: host
    volumes:
      - "./data/homebridge:/homebridge"
    healthcheck:
      test: curl --fail localhost:8581 || exit 1
      interval: 60s
      retries: 5
      start_period: 300s
      timeout: 2s
```
